### ISSUE TITLE
UX for contract update

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#179]
Please see epic (#44) for more details.

**Comment by posthnikova** [comment]
Prototype is up for review: https://invis.io/F7SG8PLDU9P

When the mastercopy is updated, we display a notification banner on Assets view (small) and in the Menu (large). You can't dismiss it. When the user taps on it, we show onboarding slides like in WalletConnect. The slides tell about what happened and why you should update, there's a link to our blog. There's also a description of the process of updating and a mention of network fee. The updating itself looks like a normal transaction with 2FA confirmations. Transaction appears in transactions list. 

In case of multiple Safes the notification only relates to currently active Safe. Each Safe has to be upgraded individually. 

Just updating Safe through App store/Google play doesn't update the contract. Recovering Safe also doesn't update the contract, it has to be updated separately.

**Comment by biocom** [comment]
Some notes/feedback:

- SECURITY UPDATE AVAILABLE -> In the context of the app I would expect that a mere 'app' update is available which will update/improve the 'security'. I think we should be more explicit about *what* kind of update is available. E.g.: 'Update your Safe contract!' or .. 'Safe contract security update available'. Just trying to convey the idea.
- In general the expectation is that a user always wants to be secure and have the latest version: What happens if I, as a user, decide to not update yet/at all? Will my Safe continue to work? For how long? If I decide to not update at all, can I dismiss this message?
- Should we start showing in the app (somewhere) what smart contract version the current Safe is using?
- Left some comments on inVision, but in terms of communicating the feature I would heavily focus on the 'audited', 'increase security' and 'your funds/assets enjoy the highest security standard available' aspect. E.g. sell the users on updating, given it does require a bit of effort and tx. fees.

**Comment by posthnikova** [comment]
New version is up for review https://invis.io/F7SG8PLDU9P

What's been done:

• Rewrote texts after comments on invision
• Added contract version in the Menu
• New icons

> What happens if I, as a user, decide to not update yet/at all? 

@biocom I added a mention that the Safe will still continue to work. 

> I think we should be more explicit about what kind of update is available

I called it "security update" on the Assets view because it's more general and doesn't require knowledge about what smart contract is. On extended banner in the Menu it's more detailed.

**Comment by lukasschor** [comment]
I really like the new icons. 🤘 Made some minor comments on the texts in invision, but looks in general good to me.

**Comment by tschubotz** [comment]
Same, like the new icons and generally these 3 slides. They seem much more logical now :)

**Comment by KristinaMayman** [comment]
The icons are great, especially the Safe flying into space :)

**Comment by biocom** [comment]
Looks good, love the icons. Now, should we be worried users will ask us how to re-collect their Safe from space....? 👨‍🚀

**Comment by posthnikova** [comment]
Some text updates and refined icons: https://invis.io/F7SG8PLDU9P

**Comment by tschubotz** [comment]
I like it. Good to go from my end.
I also sent Stefan a DM to take look if he has any concerns. Will keep you posted if anything comes up.

**Comment by posthnikova** [comment]
Android is ready: https://invis.io/DVT3SYCZK4A

**Comment by lukasschor** [comment]
Ux Sync: Looks good

**Comment by posthnikova** [comment]
Screens are on zeplin. Android: https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5d42b7d3959bdc2bdbec1565. iOS: https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5d42b8a374c7212be17e0826

**Comment by lukasschor** [comment]
Screens are on Lokalise now.
