### ISSUE TITLE
Reveal password option in password fields

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#243]
Please see epic for details

**Comment by posthnikova** [comment]
Create password, Unlock, Change password on Android: https://invis.io/UDQF6KQB54V

iOS: https://invis.io/PYPF44ESJ6X

We had green check/error icons in the fields to indicate success/error. Now because of the eye icon success/error is indicated by the text below the field:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/009a8029-03d4-488d-ba38-b6a3a8f7f4bd)

I have another version but I don't like it that much:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/1dbbf35d-2a87-4680-9402-788962a44e32)

**Comment by KristinaMayman** [comment]
I also like the version without the check marks better. And would the password be revealed only if the user is holding the finger on the eye? Or does it work like a toggle?

**Comment by posthnikova** [comment]
Final designs for iOS and Android:
https://invis.io/PYPF44ESJ6X
https://invis.io/UDQF6KQB54V

**Comment by DmitryBespalov** [comment]
approve :+1: let's do it!

**Comment by rmeissner** [comment]
look good to me (this is part of the material design lib on android, so should be easy to implement)

**Comment by posthnikova** [comment]
Screens are on zeplin.

iOS:
Launch https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c49cefc7a8bebbfe8b3671f

Create password https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c52c29e9696de3093f17f29

Change password https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c6695f7eca40f4676c75c2a

Android: 
Launch https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c4eef0659063d6277d721a9

Create password https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c5c5ea12d78a204fca15eb0

Change password https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c6569fd5a5404463af4bf4d
