### ISSUE TITLE
Automated fetching of tokens based on external source.

### ISSUE THREAD

**Issue by Georgi87** [gnosis/safe#251]
# What is this feature about? (1 sentence)
This feature allows us to automatically whitelist tokens based on an external source so we don't have to manually whitelist tokens.

# Why is it needed? What is the value? For whom do we build it?
Currently, we manually whitelist tokens, which can be displayed in the Safe app. This requires manual curating. Users complained in the past about missing tokens. Not every user will reach out to us to add this missing token. By using an external, more complete source we can outsource this problem and point users to the other, existing curation process. The manual process can stay in place but we should be able to extend the whitelist automatically based on other external whitelists. In case we detect many of our users have positive balances we can make the effort to add an image.

# High-level overview of the feature
- tbd

**Comment by Uxio0** [comment]
Regarding backend I already have an script to import from etherscan, it's easy for me to add all the tokens (we will not have pictures for all the tokens, as etherscan has just low res images), but I guess it might break pagination on the clients.

What do you think @DmitryBespalov @mikheevm @rmeissner?

**Comment by Georgi87** [comment]
It looks like https://tokens.kleros.io/tokens has quite an extensive list as well. Maybe this one can be added as well.

**Comment by sche** [comment]
@Uxio0 @rmeissner currently we take 1000 tokens from the service and do not use pagination. If the number is below 1000 it should be fine for us.

**Comment by Georgi87** [comment]
Great, how is the situation on Android? @rmeissner @elgatovital

This could be a simple fix.

**Comment by rmeissner** [comment]
On android the limit is also 1k token.

The number might be above 1k therefore we should probably adjust clients or introduce a new endpoint and display less on the old endpoint. For this is might be interesting to now the final number we would get. Do you know this @Uxio0 ?

**Comment by rmeissner** [comment]
https://eidoo.io/erc20-tokens-list also has quite an extensive list

**Comment by rmeissner** [comment]
Also on android there is no search currently, which makes navigation with 1000 tokens quite cumbersome, this should be fixed in that case

**Comment by Uxio0** [comment]
@rmeissner Just for etherscan curated list there are 979. We already have some that are not present in etherscan, like the compound tokens (cDai, etc.). If we add the etherscan + eidoo + kleros ones, a lot are the same but we will have more than 1000 tokens for sure

**Comment by Georgi87** [comment]
Then let's update the limit on Android and iOS to 2k.

**Comment by sche** [comment]
This would work I think. For 1000 tokens it would be around 500KB. On iOS, we update tokens async on the app start, so there should not be any waiting time to see the tokens list in a majority of cases. On Android as I remember the tokens are fetched when the screen is loading, and 500-1000KB could be an issue in this case. Is it the reason why you would like to have an additional endpoint @rmeissner ?

**Comment by rmeissner** [comment]
500+ KB is quite large, especially if you load it on every app start (just traffic wise). On android this is less an issue, since we only load them when we want to display the list.

If we up the limit to 2k I would strongly recommend that we implement proper caching (e.g. etags). Also iOS only needs to load default tokens on app start right? This should also lower the payload size.

In general I would prefer to implement proper pagination and a server based search, as this should not be super complicated to implement. Also one of the upcoming features is to only display tokens with balance, so this would be obsolete with that.

**Comment by sche** [comment]
Caching is a good idea. Loading diffs will optimize traffic usage a lot.
On iOS, we load the full list always. It was a decision made a long time ago. If we decide with caching, loading 500KB once is not a big deal.
Regarding the pagination, we had an open question with how to display the search index (like here on the right side https://zpl.io/an7mDKk). And I think if we implement caching, there will be no big profit in pagination.
I am not aware of "Displaying tokens with the balance only" feature. I thought we wanted to display by default on the main screen tokens with a balance. But removing tokens without balance from "Add token" screen is smth new.

**Comment by DmitryBespalov** [comment]
I would add the following points:

> @sche: For 1000 tokens it would be around 500KB.
- Currently, all of the 238 tokens take 4KB of JSON, so the 1000 tokens will take 16 KB of raw JSON text. The API should support gzip, then the payload will be just 2 KB. I also tested with 20.000 tokens (332 KB raw), and it is 4KB gzipped.

> @rmeissner: If we up the limit to 2k I would strongly recommend that we implement proper caching (e.g. ETags). 
- I would bundle up the token list with every app update (updating the list before releasing new build) - so that the app has all of the tokens after it is installed. When the app starts, it can download the updated list. Here, caching with ETag is a must.
- The pagination is already supported by our API, we can use it at any time, I don't think this is an issue. Also, with local tokens database, I don't think it is needed, because:
- We can import the tokens into a local database and do a local search on the 'add tokens' screen using the usual SQL requests, this will be super fast.
- Going with API-based approach is more flexible and will use always up-to-date information, albeit slower to use due to network requests to search each time the user types in the term. Either way, can be done.

- The loading balances for all the safes that the user has should be done on API (our backend) side as it will take quite some time to execute on the nodes. Here the viable solution will be to use web-socket based API on the app side to talk to INFURa + use batching; this would speed up the updates. The downside is that every client (frontend, android, ios) will have to implement this functionality.

**Comment by DmitryBespalov** [comment]
To sum up:
- Backend: enable gzip and caching for `/v1/tokens` endpoint
- Clients - AddToken screen
  - Fetch 1st page of the tokens and display it
  - When scrolling, fetch next/previous pages
  - When searching, query the backend with the search term; display the results

**Comment by DmitryBespalov** [comment]
Do I understand right that we implement 'display tokens with balances' on the main screen as another feature?

**Comment by rmeissner** [comment]
> Do I understand right that we implement 'display tokens with balances' on the main screen as another feature?

Yes that is correct.

> Clients - AddToken screen [...]

As far as I understood we just add gzip + caching and increase the page size to 2000, so that we can stick to a single page fetch. But I am also fine with implementing pagination

**Comment by sche** [comment]
> As far as I understood we just add gzip + caching and increase the page size to 2000, so that we can stick to a single page fetch

I understood it the same way.

**Comment by DmitryBespalov** [comment]
Ok, then I misunderstood. Of course, it's preferred because in that case, we don't change the code at all 😄

**Comment by DmitryBespalov** [comment]
**Next steps**:
  - @Uxio0 please enable gzip for /tokens endpoint on staging 🙇 
  - We'll test it on iOS and Android to see if it's working fine as it is now. Otherwise, we'll need to implement server fetch with pagination. 😄

**Comment by Uxio0** [comment]
Gzip has been enabled for a while ;)

**Comment by Uxio0** [comment]
I provide an example endpoint with 2673 tokens:

https://safe-relay.mainnet.staging.gnosisdev.com/api/v1/tokens/?limit=3000

**Comment by DmitryBespalov** [comment]
**Next steps**:
- @DmitryBespalov use 3000 limit; the Caching and gzip are handled by iOS. Request profiling results: first-time load 4,4 seconds (app loads the tokens in the background, there's no "loading" in the UI); cache hit: 800 ms!.
- @Android: @rmeissner @elgatovital please check the url https://safe-relay.mainnet.staging.gnosisdev.com/api/v1/tokens/?limit=3000 if the app can handle it gracefully
