### ISSUE TITLE
Tangem ETH card as 2FA device

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#256]
Please see epic for details.

Lots of details still have to be worked out with the engineering team, hence I would start with a technical prototype first.

**Comment by posthnikova** [comment]
iOS new screens:

### Pairing flow

Setup2FADevicesList: https://invis.io/9GVERAERWNC#/399282860_Setup2FADevicesList_

Tangem_Intro: https://invis.io/9GVERAERWNC#/399282863_Tangem_Intro_. @DmitryBespalov I added "Tap 'Start'..." to the description because the card should not be held before tapping Start. 

Tangem_Intro (NFC Off): https://invis.io/9GVERAERWNC#/399282922_Tangem_Intro_-NFC_Off-_

Tangem_Intro (waiting for card): https://invis.io/9GVERAERWNC#/399282929_Tangem_Intro_-waiting_For_Card-_

Tangem_Intro (card not detected): https://invis.io/9GVERAERWNC#/399282935_Tangem_Intro_-card_Not_Detected-_. @DmitryBespalov I propose to change text here, I find "tag connection lost" not clear enough. 

Tangem_Intro (scan complete): https://invis.io/9GVERAERWNC#/399282932_Tangem_Intro_-scan_Complete-_

Tangem_Card (success): https://invis.io/9GVERAERWNC#/399283052_Tangem_Card_-success-_

### Signing flow

Send_Review2FARequired (Tangem Card): https://invis.io/9GVERAERWNC#/399283249_Send_Review2FARequired_-Tangem_Card-_

Send_Review2FARequired (waiting for Tangem): https://invis.io/9GVERAERWNC#/399283252_Send_Review2FARequired_-waiting_For_Tangem-_

Send_Review2FARequired (Tangem error): https://invis.io/9GVERAERWNC#/399283250_Send_Review2FARequired_-Tangem_Error-_

Send_Review2FARequired (Tangem rejected): https://invis.io/9GVERAERWNC#/399283248_Send_Review2FARequired_-Tangem_-_Rejected-_

Send_Review2FARequired (Tangem scan complete): https://invis.io/9GVERAERWNC#/399283251_Send_Review2FARequired_-Tangem_Scan_Complete-_

Send_Review2FARequired (Tangem - confirmed): https://invis.io/9GVERAERWNC#/399283247_Send_Review2FARequired_-Tangem_-_Confirmed-_

### Replace 2FA

Replace2FA (Tangem intro): https://invis.io/9GVERAERWNC#/399283849_Replace2FA_-Tangem_Intro-_

Replace2FA (Tangem success): https://invis.io/9GVERAERWNC#/399283848_Replace2FA_-Tangem_-_Success-_

Replace2FA_Review (Tangem card): https://invis.io/9GVERAERWNC#/399283855_Replace2FA_Review_-Tangem_Card-_

TransactionDetail (replace 2FA - Tangem card): https://invis.io/9GVERAERWNC#/399283859_TransactionDetail_-replace_2FA-_

TransactionDetail (replace 2FA failed - Tangem card): https://invis.io/9GVERAERWNC#/399283857_TransactionDetail_-replace_2FA_Failed-_ 

TransactionDetail (replace 2FA pending - Tangem card): https://invis.io/9GVERAERWNC#/399283858_TransactionDetail_-replace_2FA_Pending-_

### Enable 2FA

Enable2FA_Review (Tangem card): https://invis.io/9GVERAERWNC#/399284406_Enable2FA_Review_-Tangem_Card-_

TransactionDetail (Enable2FA success - Tangem card): https://invis.io/9GVERAERWNC#/399284541_TransactionDetail_-Enable2FA_Success_-_Tangem_Card-_

TransactionDetail (Enable2FA failed - Tangem card): https://invis.io/9GVERAERWNC#/399284543_TransactionDetail_-Enable2FA_Failed_-_Tangem_Card-_

TransactionDetail (Enable2FA pending - Tangem card): https://invis.io/9GVERAERWNC#/399284544_TransactionDetail_-Enable2FA_Pending_-_Tangem_Card-_

### Disable 2FA

Disable2FA_Review (Tangem card): https://invis.io/9GVERAERWNC#/399284786_Disable2FA_Review_-Tangem_Card-_

### Recover Safe

Recover (2FA devices list): https://invis.io/9GVERAERWNC#/399286106_Recover_-2FA_Devices_List-_

Recover Safe (Tangem intro): https://invis.io/9GVERAERWNC#/399287002_Recover_Safe_-Tangem_Intro-_

Recover Safe (Tangem card - success): https://invis.io/9GVERAERWNC#/399287070_Recover_Safe_-Tangem_Card_-_Success-_

**Comment by posthnikova** [comment]
Android:

### Setup 2FA

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/c179d32c-5ae9-4a29-86c7-159397fa7256)

###Send 2FA

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/3c94d8df-85b6-4420-ba37-27436822996f)

### Replace 2FA

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/935d6f29-d480-4102-9f84-5366cf3eca09)

### Enable 2FA

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/04e3fde9-58ca-4de8-8062-04dcf2d3ede9)

### Disable 2FA

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/53f023da-7d7e-400c-9ee5-85ba29ffcc6a)

### Recover Safe

https://www.dropbox.com/s/0we6crronp97dr6/RecoverSafe_Android.png?dl=0

**Comment by DmitryBespalov** [comment]
looks good :thumbsup:
