### ISSUE TITLE
Use checksummed addresses throughout the app

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#323]
# What is this feature about? (1 sentence)
The app will display checksummed addresses everywhere applicable.

# Why is it needed? What is the value? For whom do we build it?
- Checksummed addresses help preventing typos
- More important than displaying checksummed addresses is actually input validation, however displaying them is a first step.

# High-level overview of the feature
- Display checksummed addresses throughout the app
  - Receive screen
  - Header
  - App/safe settings
  - Tx list and details
  - 
- Address inputs should not validate for checksummed addresses, yet.
- cf https://github.com/gnosis/safe/wiki/How-to-format-addresses

**Comment by biafra23** [comment]
Since I didn't know how checksumming works: 
Your Ethereum address, as well as every other Ethereum address in existence, has two versions - one that includes uppercase letters and one that doesn’t. These are called the checksummed and non-checksummed version. Here’s an example of the same address as a:

- Non-checksummed version: 0x12ae66cdc592e10b60f9097a7b0d3c59fce2987 
- Checksummed version: 0x12AE66CDc592e10B60f9097a7b0D3C59fce29876

**Comment by elgatovital** [comment]
See CryptoExtensions from svalinn
```
fun Solidity.Address.asEthereumAddressChecksumString() =
    asEthereumAddressString().removeHexPrefix().run {
        val checksum = Sha3Utils.keccak(toByteArray())
        foldIndexed(StringBuilder("0x")) { index, stringBuilder, char ->
            stringBuilder.append(
                when {
                    char in '0'..'9' -> char
                    checksum.hexCharValue(index) >= 8 -> char.toUpperCase()
                    else -> char.toLowerCase()
                }
            )
        }.toString()
    }
```

**Comment by liliya-soroka** [comment]
Verified
app version :
android 1.12.1 -98
ios 2.0.0 (10)
