### ISSUE TITLE
Uniform transaction list view

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#353]
# What is this feature about? (1 sentence)
This makes sure that transaction list behave the same across both mobile clients and the web.

# Why is it needed? What is the value? For whom do we build it?
- Web and mobile are quite different in terms of sorting of transactions.
- The mobile clients use the client gateway, the web has lots of logic in the frontend.
- Mobile does not handle rejections yet, properly.

# High-level overview of the feature
- Mobile and web should be compatible.
- Txs with the same nonce should be displayed as competing.
- This ticket is about the tx list, tx details and rejections will be touched #356
- Transaction list should be divided in 2 part: 
  - Tx queue
  - Tx history
  - Sorting is defined here: https://github.com/gnosis/safe/wiki/Safe-transaction-states
- New screen tracking ids:
  - `transactions_queue` and `transactions_history`. See also https://github.com/gnosis/safe/wiki/Overview-screen-tracking

# What's excluded in the v1 of this feature
### History
- Enable/disable Module transactions : Do not show Unknown module or Module name
- MultiSend is not shown - instead it will be shown as “Contract Interaction” with “multiSend” action	
- Safe app information is not shown at all - It will be as “contract interaction”
- Cancelling transaction not shown at all - It will be as “contract interaction”
- Contract interaction has action name, but the split is not by the camel case - it is split by the character.
  - Action name can be long
  - Do not break the action word by character, ellipsize if it doesn’t fit
- Contract interaction when we don’t know what method is called - no example in the designs
  - Don’t show any value in the right label
### Queued
- Learn more link url will lead to help center article: https://help.gnosis-safe.io/en/articles/4730252-why-are-transactions-with-the-same-nonce-conflicting-with-each-other

# Misc

- Web ticket: gnosis/safe-react#820
- "press release": https://docs.google.com/document/d/1QwQy9J3nyTASKsd0z-5zhXRB-ojpU6jUP47XICNUAXA/edit
- Working doc: https://docs.google.com/document/d/1IFewa3cqblEC4TG_cjjFJ6wJUXcRP0luw39QuKua3eU/edit#
- Kick off meeting (part of working doc): https://docs.google.com/document/d/1IFewa3cqblEC4TG_cjjFJ6wJUXcRP0luw39QuKua3eU/edit#heading=h.uow20oku4emc
- refinement meeting 11/11: https://docs.google.com/document/d/1DI2x4QbhG9gOCuieHk__ZJy_8yXXsOYgmlP3qaBl1OY/edit

# Updates

- Oct 30, Tobi: Updates after kick off meeting
- Nov 17, Tobi: Add refinemnt meeting link
- Dec 10, Tobi: add screen tracking ids
- Dec 17, Dima: added "What's excluded in v1" section
- Dec 17, Tobi: lean more link added

**Comment by posthnikova** [comment]
My proposal for web and mobile with all possible tx types and states. 

What's been changed on the web:
• Nonces are now in the history too
• Function called for contract interactions in the list
• New tx types (Change mastercopy etc)
• Safe apps transactions now have function called in the list

What's been changed on mobile
• Next transaction
• Date sorting
• Time stamp in the queue is '... ago'
• Multiple transactions with the same nonce
• 'Replaced' status appeared
• Function called for contract interactions instead of '0 ETH' and data bytes
• Safe apps transactions are now with app logo, name and function called

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/3903691f-534a-4a7a-a817-d628bf5d569a)

**Comment by posthnikova** [comment]
Updated proposal: 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/dec8b798-6a7e-4237-979e-986ec2c142ef)

It's better to comment on Invision but due to Invision' format restrictions there are separate projects for web: https://invis.io/95ZBLISZWNP and mobile: https://invis.io/W4ZBLJ2SHMB. 

What's been done: 
• Sorting order corrected
• Removed seconds on mobile
• 'Outgoing' and 'Incoming' renamed to 'Send' and 'Receive'
• Function names instead of English
• Removed identicons on mobile
• 'Next' and 'Queue' are now in a separate tab called 'Queue'. Switching on the web is in the sidebar. Since it's not yet implemented, switching can be done inside the page like it's currently for assets https://prnt.sc/vddek8.  
• Only show executed transactions in the history. Don't show replaced or cancelled transactions. 
• A version without grouping transactions with the same nonce but with alert icons:  https://prnt.sc/vdeq3c. They can be in different sections, in this case they are less connected visually https://prnt.sc/vdepj3. We need a user test for this. We did a user test with 'grouped' version and it didn't perform very well. 

Plus a proposal on rejections/cancelling to explain where this 'Cancelling transaction' comes from. This doesn't differ much from the earlier one (discussed on Slack https://gnosisinc.slack.com/archives/C63LQTGNB/p1600766064068100). Only cancelled transaction is not shown. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/a4538e9b-db24-4d1c-bafa-325b4ddbf046)

**Comment by posthnikova** [comment]
Updated proposal. Web https://invis.io/95ZBLISZWNP and mobile https://invis.io/W4ZBLJ2SHMB. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/d8f79086-86cd-4d46-9de8-67a455d54aa9)

What's been done:

• People liked 'version from slack' more so now it's the main version. We only show tabs when there is something in the queue. Possible states: 

 - There is something in the queue and there is next transaction: https://invis.io/95ZBLISZWNP#/437164073_Transactions_-Queue_-_Tabs-_1272px_ 
 - There is only next transaction, nothing in the queue: https://invis.io/95ZBLISZWNP#/437164110_Transactions_-Next_Only-_1272px_ 
 - There is only one transaction in the queue, no next transactions
 - History only: https://invis.io/95ZBLISZWNP#/437164120_Transactions_-Nothing_In_Queue-_1272px_ 

There will be 'jumping' between these states when tx statuses change. 
Another version with less jumping is to always show the tabs queue/history ('fixed' version). In case there are no transactions in the queue we show empty state. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/603a85d5-9b30-4042-bbb2-f45410665e09)

• Transactions with the same nonce - version without grouping won.

• 'Ago' count up in the queue - let's not count seconds. So it will be something like: 
  - `Just now` if < 1 min ago
  - `x min ago` if < 1 hour ago
  - `x hours ago` if < 24 hours ago
  - `x days ago` if < 1 month ago and so on

**Comment by DmitryBespalov** [comment]
looks good to me :+1:

**Comment by posthnikova** [comment]
New iteration: web https://invis.io/95ZBLISZWNP and mobile https://invis.io/W4ZBLJ2SHMB. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/295ca670-1882-48a7-b25e-cc6b23c9bb6d)

What's been done:
• There can only be one pending transaction. Pending tx on mobile shows as 'awaiting execution'.
• Pending transaction stays in the 'next' section until it's successful.
• Same nonce - bring back the 'grouped' version.
• Removed total amount of transactions.
• Added allowance and module transactions. As discussed in the refinement meeting, we only know that it was a module transaction and which module it was. 
- Web tx list & details: https://invis.io/95ZBLISZWNP#/437959942_Tx_Details_-Within_Allowance_-_Module-_1272px_ 
- Mobile tx list: https://invis.io/W4ZBLJ2SHMB#/437960267_Transactions_-Allowance_-_Module-_
- Mobile details - within allowance: https://invis.io/W4ZBLJ2SHMB#/437960291_Transaction_Details_-Within_Allowance-_
- Mobile details - module tx: https://invis.io/W4ZBLJ2SHMB#/437960305_Transaction_Details_-Module_Tx-_

**Comment by lukasschor** [comment]
> • Same nonce - bring back the 'grouped' version.

What is the reasoning behind this?

**Comment by posthnikova** [comment]
> What is the reasoning behind this?

Transactions are associated with each other visually. With alert icons it looks like an error, while same nonce transactions are not always a result of an error, they can be initiated to cancel a transaction. 

The main reason for introducing 'separate' version with alert icons was potential conflicts on the intersection of two pages. It seems that 'separate' version is not easier to implement in this regard. That's why we returned to 'grouped' version.

**Comment by tschubotz** [comment]
> The main reason for introducing 'separate' version with alert icons was potential conflicts on the intersection of two pages. It seems that 'separate' version is not easier to implement in this regard. That's why we returned to 'grouped' version. 

This was discussed in the last refinement meeting of this feature. UX wise we prefer the grouped version. And the devs told us that the non-grouped version is not easier to implement. Hence we opted for "grouped".

**Comment by posthnikova** [comment]
Updates after quick user tests: web https://invis.io/95ZBLISZWNP and mobile https://invis.io/W4ZBLJ2SHMB.

What's been done: 
• '2 lists' version is the main version now. I'm against opening History tab automatically when there is nothing in queue because this is unpredictable behaviour. There was a discussion 'to hide tabs or always show' and which tab to show by default when you open the app, there could be different options. 
• Updated transaction list states: https://invis.io/95ZBLISZWNP#/438782607_Transactions_States_

**Comment by tschubotz** [comment]
For me, there's 4 options:

(1) always open queue, no matter if empty or not
(2) always open history, no matter if queue is empty or not.
(3) Open history when queue is empty, open queue if it's not empty.
(4) Open queue when it's not empty, but hide queue (and thereby open history) when queue is empty.

- My favorite is (3) since that opens always the tab where there's information to consume + it keeps the interface and tabs stable all the time.
- My second favorite is (4) since that one also opens also the tab where there's info to consume, however I'm afraid it could confuse to have 1 tab disappear.
- My third favorite  is (1) since I consider the queue to be more important and I don't think people check out the history super regularly.
- I'm not a fan of (2) since it would hide queued txs when there are some. I consider the queue to be more important than history.

**Comment by KristinaMayman** [comment]
I wonder if we need orange dots next to all transactions in the queue. If everything in the queue has a dot, it's not providing any information. Maybe we could remove the dot if the user has already confirmed and only other owners' confirmations are left?

I think it makes sense to take the user directly to the history if there's nothing in the queue so my vote is for (3) as well.

**Comment by posthnikova** [comment]
> I wonder if we need orange dots next to all transactions in the queue. 

Dots made more sense when there was one list. 

> Maybe we could remove the dot if the user has already confirmed and only other owners' 
> confirmations are left? 

I'm not sure the user would be able to perceive the logic behind the dot immediately. 'Awaiting your confirmation' requires action, but 'awaiting execution' also requires action, should it have a dot?
There were other ideas long ago on how to make transactions that require actions more prominent. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/5197d4a3-3454-4e56-a150-0ae7a8bd44c1)

> For me, there's 4 options:

Option 5 is remembering your last viewed tab from the last time.

**Comment by tschubotz** [comment]
> Option 5 is remembering your last viewed tab from the last time.

True, that's actually another nice option.

**Comment by biafra23** [comment]
@tschubotz @posthnikova I think we can have a vote on the 5 options (regarding the empty queue) in slack.

**Comment by posthnikova** [comment]
Zeplin:    

Android:    
Queue: https://zpl.io/VxNRDdm    
History: https://zpl.io/aNQGYve   
Next transaction only: https://zpl.io/aNlKGQn   
Nothing in queue: https://zpl.io/a35ne9N   
  
iOS:   
Queue: https://zpl.io/bAeZdkq   
History: https://zpl.io/VOGMB4Q   
Next transaction only: https://zpl.io/bJX9wk6   
Nothing in queue: https://zpl.io/V0QJZgQ

**Comment by liliya-soroka** [comment]
Verified
ios app version 2.8.0 (277)
android app version 2.8.0 - 1882rc
