### ISSUE TITLE
Add Rinkeby 'warning' label for the Rinkeby app.

### ISSUE THREAD

**Issue by biocom** [gnosis/safe#37]
_Edit by Tobi:_
## Story
As a user I am able to clearly differentiate the Rinkeby app from the mainnet app, so I don't send any mainnet ETH to a Rinkeby address.

## Background
* There were quite some people sending mainnet ETH for Safe creation to a Rinkeby address. We should prevent people from doing that.
* The Rinkeby apps are also publicly available.
* We currently only have the differentiation based on the app icons.

_Edit end_

- Initial UX proposal created by @Mettenim https://invis.io/83PN45YQRJC
- My UI proposal can be found here:
https://invis.io/X7PP4TUDZ6F
https://invis.io/EXPP4U8W5NH
https://invis.io/YZPP4UBKXMW

**Comment by biocom** [comment]
Should this label only be shown in the RECEIVE/SEND views of the app? One argument would be that those screens are where you actually will deal with potentially sending (Rinkeby) ETH.

On the other hand, having a clear consistent indicator throughout the app distinguishes clearly the Rinkeby app from the mainnet app.

**Comment by tschubotz** [comment]
Sending Rinkeby ETH is not really a monetary problem.
Sending mainnet ETH to a Rinkeby address is. 

Concerning 2.: How would send/receive screens look with this footer? Especially with a keyboard open?

I currently prefer option number 1 due to the following 2 reasons:
* We don't clutter other screen where there is no danger of sending fund from/to another network.
* On small screens, the bottom bar could be out of the visible area, right? That would defeat the purpose.

Hence, I would add an indicator on the following 3 screens:
* Start screens (very first screen when opening the app)
* Deposit screen during Safe creation.
* Receive screen (the one where we display the address QR code)

**Comment by biocom** [comment]
In general I think it's fine to have it only on those screens.

> On small screens, the bottom bar could be out of the visible area, right? That would defeat the purpose.
I'd envision the footer bar to be a fixed overlay that doesn't hide when you scroll. The reason for choosing the footer, rather than the top section is that I found it less conflicting with other elements in the view. We'd have to review if it's technically feasible.

I'll update this issue to show a better example of overlaying in the Send/Receive screens.

**Comment by biocom** [comment]
It looks like it indeed can become problematic in terms of available real estate on smaller screen devices. It appears we do have consensus around it's primary use on selected (important) screens.

In that light I would like to propose an option to have the message inline only, on the above pointed out screens by @tschubotz .

**Comment by fmrsabino** [comment]
Yes we can explore the inline message. Might work better when vertical spacing is a concern (with keyboards in the mix, even though I like the the style of the sticky warning at the bottom. Can't be missed 😅)

**Comment by biocom** [comment]
Please check proposals:
https://invis.io/ARPG0XSTJMZ#/339765462_17_-_Receive_Token
https://invis.io/ARPG0XSTJMZ#/339765463_22_Send_Token_Entered_-_7

To only show the inline 'warning' message on the SEND and RECEIVE token screens.

**Comment by biocom** [comment]
Also just noticed we need this labeling for the DEPOSIT screen (when creating a Safe) as per:
https://invis.io/83PN45YQRJC#/337163805_10_-_Safe_Overview_-_Deploy_Process

Including a link to the Rinkeby faucet. Will update this ticket once a preview is available.

**Comment by tschubotz** [comment]
I like it! I would use the same test everywhere though. 
I would use "RINKEBY TESTNET ONLY. DON'T USE REAL FUNDS." everywhere.
A link to the faucet is also a good idea.

**Comment by posthnikova** [comment]
Designs put for review here: https://invis.io/CWQ3MFV2G5X. There are two versions: integration proposal and current design.

Integration:
It seems bottom stripe doesn't go well with keyboard and home indicator: http://joxi.net/J2b4n5EiXz1JXr, http://joxi.net/DmBJaEeHw3pOKm. So on start screens I propose putting it below status bar on iOS. I added warnings to:
1) Setup Safe options
2) Make your first deposit
3) Unlock screen
4) Unlock on iPhone 6 with touch id
5) Unlock timer
6) Unlock timer on iPhone 6 with touch id
7) Send ETH
8) Overview assets

Current iOS version:
1) Setup Safe options screen
2) Make your first deposit screen
3) Unlock screen
4) Unlock timer
5) Overview assets
6) Send ETH

**Comment by tschubotz** [comment]
@posthnikova 

I agree that the bottom stripe isn't really working. If it's higher on the screen, it's more obvious imo.

Also, thanks for preparing the list. I think 2 screens are missing: 
- The receive screen where users can share their address and the QR code is displayed. It's important there since people might send mainnet ETH to the address.
- The start screen of the app. (The one where we have the button "Create password" on. It's important there since it's the first things users see when opening the app.

**Comment by biocom** [comment]
@tschubotz On what screens we need the Rinkeby indicator for Android? For now we have:
- Send Funds
- Receive Funds

Should we add for:
- Assets overview
- Deposit screen (to create a new Safe)

**Comment by tschubotz** [comment]
Let's keep iOS and Android in sync and add it on the same screen ;)

i.e. besides Assets overview and Deposit screen, there is also the unlock screen, the welcome screen and the screen where we ask you to create a Safe or restore (i.e. the assets overview when there is not Safe.)

Just to make sure we are on the same page, I would add the indicator on the following screens:

- Welcome/start screen (the one that open when you open the app for the first time.
- Make first deposit screen
- Unlock screen
- Assets overview (When Safe exists)
- Screen where we prompt the user to Create a Safe or restore (When no Safe exists yet)
- Receive screen (The one with QR code, identicon and address)
- 2 screens in send funds flow
  - Screen where user enters address and amount.
  - Review screen where user wait for Chrome extension to confirm.

**Comment by posthnikova** [comment]
Project is up for review here: https://invis.io/CWQ3MFV2G5X 

I added:
- Welcome/Start screen
- Receive screen
- Review transaction screen where we wait for browser extension to confirm

**Comment by tschubotz** [comment]
I like it!

**Comment by tschubotz** [comment]
Missing:
- Android screen updates
- Put screen to Zeplin.

**Comment by posthnikova** [comment]
Current iOS version is on zeplin:

https://app.zeplin.io/project/5b8e45a7e1140d2c63bc08d1/dashboard?seid=5c49ce14840af6bfb00f0742

zpl://project?pid=5b8e45a7e1140d2c63bc08d1&seid=5c49ce14840af6bfb00f0742

**Comment by DmitryBespalov** [comment]
👍

**Comment by biocom** [comment]
Added to production:
- Assets overview > https://zpl.io/2jvyj1O
- Send Funds > https://zpl.io/bLKJ4P6
- Receive Funds > https://zpl.io/29odq0z
- Review Transaction > https://zpl.io/brWGovW
- Welcome > https://zpl.io/2G9qEkm
- Unlock > https://zpl.io/aXwyYjM
(in progress..)

**Comment by tschubotz** [comment]
Looks all good. 
I wasn't able to fine the following 2 screens for Android on Zeplein
- [Make deposit](https://zpl.io/awWl187)
- [No Safe](https://zpl.io/boK79Qo)

@biocom could you please add them and then close the ticket?

**Comment by posthnikova** [comment]
I updated integration design because we had some changes to Send and Review screens. 
Integration designs are on Zeplin:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c51917eb02672356bfa4813

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c51917eb02672356bfa4813

**Comment by tschubotz** [comment]
Some open questions on Make deposit & No Safe.
-> Let's see if we can resolve them soon. If not, let's use the old versions and add the label there.

**Comment by biocom** [comment]
Added missing screens for production:

No Safe:
https://zpl.io/2yzwnQy

Make deposit:
https://zpl.io/agPy0v0
https://zpl.io/aNKdjoZ

**Comment by tschubotz** [comment]
have to reopen this. While writing the spec I noticed the following inconsistencies:

**Start screen**
- Android has the banner on top: https://zpl.io/2G9qEkm
- iOS has the label in the center of the screen with a link to the faucet: https://zpl.io/beoXxJB
- I prefer the iOS version since it has a link to the faucet. @biocom what do you think? 

**Make deposit**
- Android has the banner: https://zpl.io/agPy0v0
- iOS has the label: https://zpl.io/awWl187
- Since all other in app screens have banners,  I would go with the Android approach @posthnikova what do you think?

**No safe**
- Android has a banner: https://zpl.io/boK79Qo
- iOS has a label inside screen with the faucet link: https://zpl.io/boK79Qo
- I would go with iOS since it has a link to the faucet. What do you think @biocom ?

**Comment by posthnikova** [comment]
Make deposit Integration version: https://zpl.io/aByPBxA

Make deposit current production version: https://zpl.io/2vWodNY

**Comment by biocom** [comment]
**Updated:**

- Start screen: https://zpl.io/V4Oz5x4
- Deposit screen: https://zpl.io/agPy0v0
- No Safe: https://zpl.io/2yzwnQy

**Other:**
- Assets overview > https://zpl.io/2jvyj1O
- Send Funds > https://zpl.io/bLKJ4P6
- Receive Funds > https://zpl.io/29odq0z
- Review Transaction > https://zpl.io/brWGovW
- Unlock > https://zpl.io/aXwyYjM

**Comment by biocom** [comment]
@posthnikova For the larger Rinkeby banner, I was thinking if we should display the URL like:
FAUCET.RINKEBY.IO

So without https:// and uppercase. This so it matches with the rest of the uppercase text.

**Comment by posthnikova** [comment]
This looks much better. Updated:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c51917eb02672356bfa4813

https://app.zeplin.io/project/5b8e45a7e1140d2c63bc08d1/dashboard?seid=5c49ce14840af6bfb00f0742
