### ISSUE TITLE
Mobile signing v2

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#380]
# What is this feature about? (1 sentence)   

This feature adds UX improvements to mobile signing.   

# Why is it needed? What is the value? For whom do we build it?   

- Insights from first user test with click through prototype wasn't incorporated, yet.
- There is another usability test of the live app in progress which will bring more insights.
- Some users requested pk input instead of just seed phrase.
- The signing feature is not super visible right now.

# High-level overview of the feature   
**Changes after Signing on mobile user test (see [insights](https://docs.google.com/presentation/d/1exhyCWYZXq4aXUVrhijNkoz9yfNuTqEU6kb-_iSuLjU/edit?usp=sharing)) and Changes after Live signing user test **    

1. Add one onboarding screen before entering seed (includes info that importing a key will not add anything to the assets)   
1. Hide derived keys under 'Show more derived keys' button   
1. Add info about where execution needs to happen. 
   - Collect confirmations step. The user taps 'Confirm transaction'.   
   - Add more steps/info to the vertical timeline
1. Show loading indicator and 'Confirmation successfully submitted' snackbar.   
1. Execute transaction step. There is info that execution is not possible in this app. 
1. Make the mobile signing feature more apparent (via banner or something similar)
1. Allow to import a private key rather than a seed phrase (let user choose)

# Misc

- [Kick off meetings notes (Google Doc)](https://docs.google.com/document/d/1vjDlJpTGJld0mQRUwjkmY2_SS7yMPRqtADaCEeXM9QY/edit#)

# Design

[Signing on mobile v2: design decisions (Google Doc)](https://docs.google.com/document/d/1DqUNRCFpJQWS-HMM4gWzDN-ihNIA8-WoFT8ZfjPHJpw/edit#heading=h.eq8eoqliqxlt)

[iOS (Zeplin)](https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/dashboard?seid=5f744615f58f92393883e294)
[Android (Zeplin)](https://app.zeplin.io/project/5e9efc30726e106958cc43de/dashboard?seid=5f7447fa6973a665771cda13)

# Tracking

### Screen view

- New screen view identifiers: 
  - `safe_add_owner`: New screen during onboarding
  - `owner_select_account`: Info screen when adding an owner
  - See https://github.com/gnosis/safe/wiki/Overview-screen-tracking for screenshots.

### User actions

- New `user_` action events
  - `user_banner_owner_skip`: Triggered when clicking the `x` on the banner to ask users to import their owner key.
  - `user_banner_owner_import`: Triggered when clicking the `Import` on the banner to ask users to import their owner key.
  - `user_onboarding_owner_skip`: Triggered when clicking the `Skip` during onboarding, after adding a Safe when asking users to import their owner key.
  - `user_onboarding_owner_import`: Triggered when clicking the `Import` during onboarding, after adding a Safe when asking users to import their owner key.
  - Also documented on https://github.com/gnosis/safe/wiki/Tracking
- New param for `user_key_imported` event
  - `import_type` (String): `seed` or `key`
  - Also documented on https://github.com/gnosis/safe/wiki/Tracking

# Updates   

- Sasha, Nov 20: add what this feature is about, add high-level overview (changes after Signing on mobile user test)
- Tobi, Jan 5: Remove `Misc` section
- Tobi, Jan 6: Updates after kickoff meeting
- Dirk, Jan 13: Adding latest designs to ticket description
- Tobias, Jan 15: Adding Tracking info
- Dirk, Jan, 18: Removed signing design without changes to current implementation
- Dirk, Jan, 19: Adding links to Zeplin designs
- Dirk, Jan, 21: Adding links to `Signing on mobile v2: design decisions`
- Dirk, Jan 28: Removed `read only` flag feature

**Comment by posthnikova** [comment]
iOS: https://invis.io/4EYSS957HQX
Android: https://invis.io/A3YSSA5TQ9E

**User flows overview**

Import:    

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/5d53015a-0933-48ee-af54-dd4e0bb642ee)

Sign:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/70a67c72-bf04-47de-82e9-a7acf301a6c7)

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/3cead4d4-9c47-4d39-8691-cb78fbd5b50c)

**Comment by posthnikova** [comment]
Changes after live signing user tests. The recommendations were:   

### 1. Add an option to import key in the process of onboarding
The options we have are:
1) Offer to import an owner on Success screen after loading Safe. Only applies to users who load Safe. Doesn't apply to users who have Safes already loaded. 
2) Banner on Assets. Only applies to users who have Safes loaded. 
3) Ask before loading the first Safe what they want to do, do they want to load a Safe only or an owner key too. Only applies to new users who don't have Safes loaded. Doesn't change anything for user who have Safes loaded. After you enter Safe name it takes you to entering seed immediately. 
4) Onboarding with info about features before we offer to load the first Safe. Only applies to new users who don't have Safes loaded. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/0ccbaa13-08ba-408f-84b5-21d7982b0402)

I would go with the combination of 3 and 2. 

### 2. Explain what is fallback handler. 
I propose we add a short explanation (3–5 lines) without the need to tap on question icon. There might be a 'Learn more' link. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/6bef0ac5-d70f-4735-beb6-acd9ce1c934d)

### 3. Make small headers more prominent. 
We can merge these two styles but that would break the hierarchy. Tabs type size should be bigger than section header size because it's a higher header level.

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/f3ea6290-f7e0-4588-ad20-726e1bd1bd26)

**Comment by KristinaMayman** [comment]
Thanks for posting these.

I think ideally we would do both option 1 (offer import after loading) and 2 (banner on Assets). That should cover both the new and existing users.

I think the explanation is good but it would probably even be sufficient if we just had a link to the article with the text saying something like "What is a fallback handler?"

I think the hierarchy argument is valid. We can keep an eye out for whether the discoverability of the small headers is a persistent problem, if yes, we can return to this improvement and think of how it can be done.

**Comment by DmitryBespalov** [comment]
1. I like option 1 because it is straightforward and in the context.
2. Looks good to me
3. Looks good, but maybe we can change the tab titles to be "Safe" and "App", and then make the font even bigger... but that would affect tabs in all other screens. Don't know, you decide 😄

**Comment by sche** [comment]
I like (1) Safe Loaded and (2) Banner

(3) No safe loaded with two buttons I like less. I would suggest to display it like in (1) if this is the first safe always.

**Onboarding (Signing on mobile)** - cards look like actionable for me. Do we want to display such onboarding screen always when a user wants to import a signing key for the first time? If yes, I would rather go with classic swiping onboarding.

**Comment by tschubotz** [comment]
> 1. Add an option to import key in the process of onboarding

I shared the opinion of the others: I like option 1 and 2 most. I prefer 2 a bit more since it would cover also the case of people who have already loaded a Safe. And they have to specifically dismiss it (I hope that makes them read it). + I remember that we had banners in the legacy app for e.g. contract update which felt quite nice in my opinion.

> 2. Explain what is fallback handler.

Love the simplicity of this fix. I'm happy to write a help center article on this if we decide for this option. I share Kristina's opinion: Instead of explaining it, I'd just link the article.
In case we go with the current version and more text I would adapt the text a bit. But I'd have to think about a concise version a bit more.
Also, something I noticed: The default Fallbackhandler is actually called Default**C**allbackHandler (https://github.com/gnosis/safe-contracts/blob/development/contracts/handler/DefaultCallbackHandler.sol) 🤯

> 3. Make small headers more prominent.

I don't have a strong opinion here to be honest.

4. Import private key

Some users said they didn't want to import their seed phrase and preferred to put in raw private keys. Is this something you considered to add?

**Comment by lukasschor** [comment]
> 1. Add an option to import key in the process of onboarding

I would vote for having both option 2 and option 4 simultaneously.

Option 2: Highlights the signing feature also for existing users. It's very prominent, and it doesn't make the onboarding flow more complicated. While in option 1 we allow to skip the key import, we would still nudge the user to do so and therefore might add additional friction.

Option 4: I like having an elevator-pitch when downloading new apps, so I know exactly what the key features of the app are. It also re-assures to the user that they can take value out of the app. Also, I don't see much potential downside for adding this option.
In case we would go ahead with this option, I would have some comments around the copy though.

**Comment by liliya-soroka** [comment]
I like the options 2 , 4 and think that It make sense to have both of them at the same time. The option 2 will cover all our current "Import owner key" introduction needs for new users and already existed users. The option 4 is nice at the whole as a first intro for new users with any level of knowlidg.
I like options 1 and 3 less, as from my point of view it may confuse users and show that there is "one safe"<->"one owner key" connection in case of a few safes. They may seacrh for the way to add a few keys at the same time for diff safes. Also these options will cover only new users

**Comment by posthnikova** [comment]
Changes after kickoff meeting. 
1) Show more derived keys

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/6d09bf44-f45e-48f0-8a3c-0426a18c65f4)

2) Discoverability
We have 6 votes for option 1 and 4 votes for option 2. So no changes here. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/7138598f-a2d6-4595-b983-1d21e70a2cdb)

3) Vertical stepper
I tried it and it somehow works on mobile but doesn't work on the web. The timeline has to be in sync between platforms so the web has to adapt as well. On the web it's more complex because there's execution and cancelling. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/05eb2628-b42f-481c-8632-4f9e06dbd485)
![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/0c47db3c-b28d-411f-a216-657590b35f0c)

It doesn't work on the web because the information is in the wrong order and out of context here. Information about gas, how much to pay and when to pay depends on an action the user is performing (confirming or executing, or cancelling). And in transaction details we don't know which action the user chooses to perform next. 'Execute transaction' checkmark makes things more complex, it's unclear if it applies both to 'Confirm' and 'Cancel' buttons or not. 

Overall I'm not sure we should redesign the timeline now. It has been tested a lot. Horizontal steppers were reused from the web interface popups (https://zpl.io/beQJRxp, https://zpl.io/VDL0y33, https://zpl.io/VQk5k3W, https://zpl.io/VDXKYyJ) and these have been tested as well in Rejections user tests, they performed quite well.

**Comment by tschubotz** [comment]
> 4) Vertical stepper: I tried it and it somehow works on mobile but doesn't work on the web. 

On web there is no separate tx details page, it's a bit different. It's a lot of information now. 
Why doesn't it work though? Wouldn't the cancellations move out to a separate "cancellation tx" with tx list v2?

Either way, would it be a problem if mobile and web do it a bit different though? After all on web, we have so much more vertical screen real estate compared to mobile.

Also @posthnikova could you explain again why "execute" and "submit to chain" are different steps? I didn't understand that in the last meeting.

**Comment by posthnikova** [comment]
> Why doesn't it work though? Wouldn't the cancellations move out to a separate "cancellation tx" with tx list v2?

@tschubotz It doesn't work because there cannot be a 'universal' timeline on the web. This information doesn't belong to transaction details, it belongs to the action you're performing in confirmation/execution popups. Confirmation, execution, cancelling have their own specific timelines, the steps are different. The number of steps depends on whether you check 'Execute' checkbox. If we show this timeline in transaction details there is a question what do we show in confirmation popups. Do we have to remove confirmation popups completely? Will there be duplicate information? 

> After all on web, we have so much more vertical screen real estate compared to mobile.

The question wasn't about space, it was about removing two screens. Overall we try to reduce differences between web and mobile. 

> could you explain again why "execute" and "submit to chain" are different steps? 

This timeline was designed after we introduced off-chain signatures. The purpose of these steps was to explain where the user is in the process and when to pay gas. The users still thought confirmations are on-chain, hence this 'submit to chain' as the final step. 
I separated 'execute' from 'submit to chain' because at some moment it could be 'collect confirmations from owners, execute, pay gas and submit to chain', which is too long. Separate steps are easier to perceive. Technically, this is one step.

**Comment by tschubotz** [comment]
> @tschubotz It doesn't work because there cannot be a 'universal' timeline on the web. This information doesn't belong to transaction details, it belongs to the action you're performing in confirmation/execution popups. Confirmation, execution, cancelling have their own specific timelines, the steps are different. The number of steps depends on whether you check 'Execute' checkbox. 

I thought of this always as a universal timeline 🤔 
Cancelling had a different  / overlapping/ competing timeline. But not with the new tx list layout.

> If we show this timeline in transaction details there is a question what do we show in confirmation popups. Do we have to remove confirmation popups completely? Will there be duplicate information?

Right, then it would only be duplicate. But I thought it's more important to have it always accessible in the tx details rather than only temporarily in the popup.

**Comment by KristinaMayman** [comment]
> 2) Discoverability
> We have 6 votes for option 1 and 4 votes for option 2.

I really don't see them as mutually exclusive. The users that have already added their Safes can see the banner the next time they open the app and the new users that are adding their first Safe will see the button to import the key once they go through that process.

**Comment by posthnikova** [comment]
@KristinaMayman I mean they both won.

**Comment by posthnikova** [comment]
Changes after refinement meeting. What's been done:
• Add private key - there were two options to enter private key and seed phrase, with one combined field and with two separate fields. I prefer the version with one field. In this case you can either type or paste.

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/29199ddf-3098-4a76-a000-4c529c3ec95c)

• Discoverability - no changes, keep options 1 and 2. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/a1b59482-1451-4731-af77-6c37f11f48a3)

• Sign - there was an open question, do we need these screens with timeline? https://prnt.sc/wmkbx0. I propose we just remove them on mobile and keep this 'Execution is not possible' alert https://prnt.sc/wmkcek. I wouldn't redesign the timeline now for reasons outlined above.

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/776730db-9cf5-418c-b2ab-a727c853b681)
![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/674df2a1-9217-48bf-8ecc-aafe4190733a)

• Remove owner - no changes. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/c4118358-4454-44ae-a116-e3dc3716d35a)

**Comment by lukasschor** [comment]
@posthnikova Question regarding the "Discoverability" screens:

Right now it is only possible to import one private key. What would be the expected behavior if the user already imported a key and is adding a new Safe. I assume in that case we could not ask to add a key? As the user already knows about the ability to do so and adding a new key would remove the old one which would not be desirable.

**Comment by posthnikova** [comment]
@lukasschor Then we don't offer to import owner key, after entering name (https://zpl.io/amZ4nzK) you are directed to balances as usual.

**Comment by tschubotz** [comment]
Thanks for the screens, I like it! 

(1) `Default` and `#1` when importing key.

![image.png](https://images.zenhubusercontent.com/57add4fee40e5714b16d4969/f797989d-8420-4d14-a35a-10399205edd9) when importing a key, technically the `#1` and `default` don't add any info. It's just 1 address. So I think that could be left out in that case

(2) Import key during Safe add flow
![image.png](https://images.zenhubusercontent.com/57add4fee40e5714b16d4969/814a41ee-9e42-40cc-94a4-10905680f824)
I think this should be left out in case there is already a key imported since we currently only allow import of 1 key.

(3) Does that banner re-appear?

![image.png](https://images.zenhubusercontent.com/57add4fee40e5714b16d4969/cab4d217-3c76-4a68-9970-643f72f57d22)

I would assume that in the banner would be shown the first time a user adds a Safe without importing a key. And it would not re-appear when adding a 2nd Safe. Is that correct?

**Comment by jpalvarezl** [comment]
I have one question regarding the `Default` owner address. Does that correspond to the first address derived from the seed phrase? Or does it correlate to the selected safe in any way? 

I personally find it a bit cumbersome that the current implementation needs the user to be aware of the owners of a certain safe (by having the safe opened in a different interface), in order to select an owner address that the backend will accept for signing. 

Would it be helpful to somehow hightlight for the user the addresses that correspond to owners of currently active safe in the app?

**Comment by posthnikova** [comment]
> technically the #1 and default don't add any info. It's just 1 address

@tschubotz We can reuse the UI we have for Safes:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/d6003609-9a15-42fd-b305-dd8fee9ca242)

> I think this should be left out in case there is already a key imported since we currently only 
> allow import of 1 key.

Yes. 

> I would assume that in the banner would be shown the first time a user adds a Safe without 
> importing a key. And it would not re-appear when adding a 2nd Safe

I would prefer we don't show both options at the same time. 
New user adds their first Safe -> offer to import owner key, don't show banner after Safe is added (even if they skipped key import). 
User who has Safes opens the app -> show banner on app start. 
User who has Safes adds another Safe -> offer to import owner key. It is only offered once. When they skipped key import, don't show anything for subsequent Safes. 

> Does that banner re-appear?

I would prefer to show it a couple of times because some people dismiss banners without reading. This isn't an error or a mandatory upgrade so it shouldn't appear forever.

**Comment by posthnikova** [comment]
**Zeplin**   
iOS: https://zpl.io/b6Xe70y
Android: https://zpl.io/bJXwABJ

**Comment by lukasschor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile Signing v2](https://trello.com/c/Xb8YOcD0/54-mobile-signing-v2)

**Comment by liliya-soroka** [comment]
Added test cases:
1. "Import owner key" onboarding during Load safe flow - https://gno.testrail.io/index.php?/suites/view/4&group_by=cases:section_id&group_order=asc
2. Banner test cases - https://gno.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc
3. Import owner key intro as the first step of Import owner key - https://gno.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc
4. Private key importing - tbd
5.  Derived key list page - v2 - tbd

**Comment by liliya-soroka** [comment]
Verified
app version:
ios - 2.9.0 (294)
android 2.9.0 -1991rc
