### ISSUE TITLE
Introduce app and/or confirmation passcode

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#394]
# What is this feature about? (1 sentence)

# Why is it needed? What is the value? For whom do we build it?

- This relates to the problem that for some users "Storing a key on mobile doesn't feel secure"
- Currently, even when importing an owner key, no app password is set. We rely on the access control of the device.
- Banking apps and other Ethereum wallets have passcodes.
- It should not be possible to confirm txs by someone who is not authorized. An app or confirmation password is an attempt to prevent that.

# High-level overview of the feature

- User is prompted to set a passcode after importing a key.
- User can change the passcode via the app settings
- Passcode is required when importing an owner key
  - Existing users that had a key imported need to be migrated, i.e. asked to set one.
- Passcode is 6 numbers
- In case the user forgets the passcode, they can reset it, thereby wiping all imported owner keys.
- Passcode is required for confirming/rejecting transactions.
- User can optionally use touch id/biometric info as well. (cf. how Argent prioritizes touch id)
- Add a section to the help center article with the changed security measures #392

# Misc

- Kickoff doc: https://docs.google.com/document/d/1xTpgqdg6V4h64-xQ0VMg8zv-Pb6wKLMEdd6wywVeZ8U/edit#
- Spec v1: https://docs.google.com/document/d/1G-3oHorCy46Xegegsvrd4FgA6rSxc2WrulaeSp_bspI/edit#

**Comment by tschubotz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Introduce app or confirmation password](https://trello.com/c/FsKdcqzM/78-introduce-app-or-confirmation-password)

**Comment by biafra23** [comment]
> Passcode is required when importing an owner key 

Does that mean, the app should ask for the password and check, that it is correct (matching the previously entered pasword)?

**Comment by biafra23** [comment]
@tschubotz 

What about allowing only a certain number of wrong passcode entries. For example 5. After 5 wrong passcode entries the keys are erased. Possible DOS attack.

**Comment by lukasschor** [comment]
> @tschubotz
> 
> What about allowing only a certain number of wrong passcode entries? For example 5. After 5 wrong passcode entries the keys are erased. Possible DOS attack.

Interesting though to basically mimic the Ledger behavior. Because as with Ledger we also don't want that the key on the device exists without a backup (i.e. that the key on mobile is merely an easy-access "copy" of the key, given there is a risk the device is lost / broken). So having a less secure passcode coupled with a mechanism erase the private keys in case of too many failed attempts might be an interesting approach.

**Comment by tschubotz** [comment]
> Does that mean, the app should ask for the passcode and check, that it is correct (matching the previously entered passcode)? Or does this mean, a passcode has to be set prior to importing an owner?

I was thinking the later: Passcode needs to be set prior to importing an owner.

> How do we handle multiple owners imports? Will they all use the same passcode?

Yes, I would use the same passcode. Remembering different passcodes per keys sounds not viable to me.

> What about allowing only a certain number of wrong passcode entries? For example 5. After 5 wrong passcode entries the keys are erased. Possible DOS attack.

In case we allow biometric authentication, 5 failed attempts might be easily reachable with a wet finger. Would be really annoying if that wipes all keys.
Currently I think that this logic is not needed right now for this version.
Still, interesting idea for a trade off between difficualty of the passcode and security of the key.

**Comment by posthnikova** [comment]
Very quick wireframes with the ideal case (passcode is optional, biometrics are optional, the passcode is used for app open or signing). 

**1) Create passcode and enable biometrics**   

The user is prompted to add a passcode after install, app update, or when they imported an owner key. Open question: should we allow skipping it?   

![image](https://user-images.githubusercontent.com/45787536/107379497-4574ad80-6aed-11eb-93fa-047427c9ffa4.png)   

**2) Change passcode**   

![image](https://user-images.githubusercontent.com/45787536/107380604-4bb75980-6aee-11eb-8ede-18c459d6922c.png)   

**3) Forgot passcode**

If the user forgets the passcode, they can reset it, this removes all imported owner keys. Open question: does resetting a passcode turn it off completely or is the user required to create a new passcode? 

![image](https://user-images.githubusercontent.com/45787536/107380678-5f62c000-6aee-11eb-8298-c4e5d9d1507f.png)

**4) Turn passcode off**   

Open question: should we allow turn a passcode off at all? Maybe when there is no owner key?    

![image](https://user-images.githubusercontent.com/45787536/107381006-b072b400-6aee-11eb-8a44-36f7ad74b389.png)   

**5) Sign**   

![image](https://user-images.githubusercontent.com/45787536/107381037-bb2d4900-6aee-11eb-90b8-2479605071ae.png)

**Comment by liliya-soroka** [comment]
From the screens, I have a feeling, that I can not use only biometrics without a passcode. Am I right ?

**Comment by KristinaMayman** [comment]
These look good! A couple of comments:

I feel like turning a passcode off is not necessary, maybe we can skip adding that feature for now and see if we get feedback from users that it's something they would like to be able to do?

The other thing is that for me, the "Security" button in the App Settings might get overlooked because people might group it together with the terms and license and privacy policy, which tend to be glossed over. How about putting a space between "Security" and the rest of the app setting, similarly to how there is a space before "Advanced"? That way we're also separating the settings that can be changed from merely informative part of the settings.

**Comment by tschubotz** [comment]
Thanks for these proposals! I don't have much comments.

> Open question: should we allow turn a passcode off at all? Maybe when there is no owner key?

I think we should either allow to turn it off the passcode always (no matter of key or not) or require it always (not matter if key or not). Reason being that this way we would have to keep less special cases in mind.
I'm fine either way, but I would lean towards the optional variant since that provides the biggest flexibility.

Regarding: 

> 3) Forgot passcode

how about saying: you need to reinstall the app? Just to keep things simpler.

**Comment by DmitryBespalov** [comment]
@tschubotz reg. reinstalling - I'm not so in for it because it wipes out user data (safes and names)

**Comment by posthnikova** [comment]
Final designs. What's been changed:
- Removed biometrics for v1
- Removed settings 'Require to open app', 'Require for confirmations', only global disable remains
- Added error states
- Added discoverability banner
- Removed 'Next' buttons
- Removed success screens in favor of snackbars
- Renamed menu item in the settings into 'Passcode'

### Create passcode   

![image](https://user-images.githubusercontent.com/45787536/108490466-10155000-72a3-11eb-8931-90ff3c339173.png)

### Errors   
Validation happens when all digits are entered. In case of error a message appears and the input clears. 

![image](https://user-images.githubusercontent.com/45787536/108490644-3f2bc180-72a3-11eb-8826-4b128fda9e3d.png)

### Banner   

![image](https://user-images.githubusercontent.com/45787536/108490756-63879e00-72a3-11eb-9362-c79c3d2f0c92.png)

### Change passcode   

![image](https://user-images.githubusercontent.com/45787536/108490806-713d2380-72a3-11eb-80fb-ccf154a4be88.png)

### Forgot passcode   

![image](https://user-images.githubusercontent.com/45787536/108490882-8619b700-72a3-11eb-9c69-0c9d1b3914e9.png)

### Disable passcode    

![image](https://user-images.githubusercontent.com/45787536/108490930-95006980-72a3-11eb-9264-cb3c72f969f4.png)

### Sign    

![image](https://user-images.githubusercontent.com/45787536/108490960-9e89d180-72a3-11eb-8e77-8d54940912fa.png)

> I feel like turning a passcode off is not necessary, maybe we can skip adding that feature for now

@KristinaMayman Since a passcode is completely optional you should be able to disable it. 

> How about putting a space between "Security" and the rest of the app setting

@KristinaMayman Done.

**Comment by tschubotz** [comment]
Thanks for preparing! I think they look good from my point of view. Just found 1 thing:

![image](https://user-images.githubusercontent.com/1380529/108492356-58357200-72a5-11eb-87af-fbbe4bd3b913.png)
![image](https://user-images.githubusercontent.com/1380529/108492949-080adf80-72a6-11eb-962f-b30c31c2c8f5.png)
![image](https://user-images.githubusercontent.com/1380529/108493082-3688ba80-72a6-11eb-8a1e-b5cbd0aaba43.png)

That's not true for v1, right? In v2 it'll just be "The passcode will be needed to sign transactions."

**Comment by sche** [comment]
Looks good to me. Nice job 👍

**Comment by elgatovital** [comment]
:+1:

**Comment by posthnikova** [comment]
**Zeplin**
iOS: https://zpl.io/bW637qx
Android: https://zpl.io/VY6zMnn 

> That's not true for v1, right? In v2 it'll just be "The passcode will be needed to sign transactions."

@tschubotz Corrected.

**Comment by liliya-soroka** [comment]
waiting for the crash on android to be fixes for import owner key flow to finish tracking screens check

**Comment by liliya-soroka** [comment]
Verified
android app version 2.14.0 -2417rc
ios app version -2.12.0 (345)
