### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#75]
# Problem statement
* In order to improve the app we need some anonymized quantitative data.

**Comment by DmitryBespalov** [comment]
Would be good to have categories of data we need, for example:

- user interface actions (screen views, button presses, impressions)
- business events (transaction events - submitted, succeeded, failed, rejected; safe events - created, failed to create, hanging for more than 10 minutes, settings changed)
- performance events (transaction processing time, safe creation time)

Even rough understanding of what types of questions we would like to ask would help to clarify the scope of tracking, so I'd request more information on this (questions we want to know), and categories of events we'd like to collect.

Also, this should be specified in our privacy policy, and we might think about having a "do not track" toggle inside the app.

We also could have a "do not send developer reports" or similar to disable the crash tracking, if a user chooses to do so.

Finally, if we are planning any marketing or advertising campaigns, we also might need the advertisement performance tracking (how many installs from the ad, or what action user performs after viewing the ad) - such services as Adjust might be helpful.

**Comment by rmeissner** [comment]
For this estimate: Integrate firebase + Screen views + Button click

**Comment by tschubotz** [comment]
- iOS and Android should track to the same Firebase project.
- Staging and production environments should be kept separate.
- https://support.google.com/firebase/answer/6317486?hl=en <- these automatically collected user properties should be tracked.
- Advertising ID should not be collected (not part of our terms/privacy policy right now) https://firebase.google.com/support/guides/disable-analytics

**Comment by DmitryBespalov** [comment]
Screen view tracking information:
https://docs.google.com/presentation/d/1w1tOKpfPcgtPacY_LIHSwOhprz4d91ZJ-FNJK50zxu8/edit#slide=id.g4fec7dc763_0_60

**Comment by DmitryBespalov** [comment]
I'd like to note down the decisions that we took during tracking discussion:

1. Since firebase limits number of event types to 500, and you cannot remove existing event type nor increase the limits ([Firebase limits](https://support.google.com/firebase/answer/9237506?hl=en&ref_topic=6317484)), we are going to use `gnosis_screen_view` for event type, and pass `screen_name` as a parameter to the event. Otherwise, if we track each screen view as a separate event type, then it will relatively quickly hit the 500 events mark (taking into consideration 2 platforms, and button clicks).
2. For making funnels, we keep some existing events for now, although they are deprecated.
3. For making funnels with BigQuery, you can take a look at the articles below

- <https://medium.com/firebase-developers/how-do-i-create-a-closed-funnel-in-google-analytics-for-firebase-using-bigquery-6eb2645917e1>
- <https://medium.com/firebase-developers/bigquery-and-google-analytics-for-firebase-lets-create-a-multi-part-funnel-420d837c1f5e>
- <https://stackoverflow.com/questions/53560206/firebase-closed-funnels-with-parameters>
- <http://online-behavior.com/analytics/funnel-analysis>

4. Screen view events are tracked on screen appearance. That means, if the screen was occluded by another screen, or app went to background and then returned to the screen again, then the screen view event will be triggered every time the screen is shown to the user.

**Comment by DmitryBespalov** [comment]
This is the list of all tracking events with their parameters and overview where and when they are implemented:

https://docs.google.com/spreadsheets/d/1KVaeOZ21aaNgR2jc5JM69gj0NWaOdOhlyhYXUMzh1l4/edit#gid=0

**Comment by DmitryBespalov** [comment]
As part of the implementation plan, I'd note here the need to make a system tracking test that shows that the events generated by screens are tracked and displayed correctly in the Firebase

**Comment by DmitryBespalov** [comment]
Note, that on iOS, by default, when app is minimized and maximized again, the screen does not receive "appear" event, and we need to handle that separately.
